import {useEffect,useState} from 'react';
import {App as AntApp,Avatar,Button,Card,Col,DatePicker,Descriptions,Drawer,Dropdown,Form,Image,Input,InputNumber,Layout,Menu,Modal,Popconfirm,Row,Select,Space,Statistic,Table,Tag,Typography} from 'antd';
import {ApartmentOutlined,CalendarOutlined,DashboardOutlined,DeleteOutlined,EditOutlined,HomeOutlined,LogoutOutlined,MenuFoldOutlined,MenuUnfoldOutlined,PlusOutlined,ReloadOutlined,TeamOutlined,UserOutlined} from '@ant-design/icons';
import dayjs from 'dayjs';
import {api} from './api';

const {Header,Sider,Content}=Layout;
const menuItems=[{key:'dashboard',icon:<DashboardOutlined/>,label:'数据概览'},{key:'listings',icon:<HomeOutlined/>,label:'房源管理'},{key:'appointments',icon:<CalendarOutlined/>,label:'预约管理'}];
const emptyListing={title:'',rentType:'整租',district:'朝阳区',subway:'',price:5000,layout:'1室1厅',rooms:1,area:50,floor:'5/18层',tags:[],imageUrl:'',description:'',rating:4.8,reviewCount:0,landlordName:'张先生',landlordPhone:'13800000000',latitude:39.9,longitude:116.4,status:'published'};

export default function Root(){return <AntApp><AdminApp/></AntApp>}
function AdminApp(){
 const [token,setToken]=useState(localStorage.getItem('zufang-admin-token'));
 const [page,setPage]=useState('dashboard'); const [collapsed,setCollapsed]=useState(false);
 if(!token)return <Login onLogin={value=>{localStorage.setItem('zufang-admin-token',value);setToken(value)}}/>;
 const logout=()=>{localStorage.removeItem('zufang-admin-token');setToken(null)};
 return <Layout className="admin-layout"><Sider collapsible collapsed={collapsed} trigger={null} width={230}><div className="brand"><span>暖</span>{!collapsed&&<b>暖居管理台</b>}</div><Menu theme="dark" mode="inline" selectedKeys={[page]} items={menuItems} onClick={({key})=>setPage(key)}/></Sider><Layout><Header className="admin-header"><Button type="text" icon={collapsed?<MenuUnfoldOutlined/>:<MenuFoldOutlined/>} onClick={()=>setCollapsed(!collapsed)}/><div className="header-right"><Avatar icon={<UserOutlined/>}/> <span>管理员</span><Button type="text" icon={<LogoutOutlined/>} onClick={logout}>退出</Button></div></Header><Content className="admin-content">{page==='dashboard'?<Dashboard/>:page==='listings'?<Listings/>:<Appointments/>}</Content></Layout></Layout>
}

function Login({onLogin}){const {message}=AntApp.useApp();const [loading,setLoading]=useState(false);const submit=async values=>{setLoading(true);try{const res=await api('/admin/login',{method:'POST',body:JSON.stringify(values)});onLogin(res.token)}catch(error){message.error(error.message)}finally{setLoading(false)}};return <div className="login-page"><div className="login-art"><div><span className="logo-mark">暖</span><h1>让每一套好房<br/>都被温柔看见</h1><p>暖居租房 · 一站式运营管理平台</p></div></div><Card className="login-card"><Typography.Title level={2}>欢迎回来</Typography.Title><Typography.Text type="secondary">登录管理暖居房源与预约</Typography.Text><Form layout="vertical" onFinish={submit} initialValues={{username:'admin',password:'admin123'}}><Form.Item label="账号" name="username" rules={[{required:true}]}><Input size="large" prefix={<UserOutlined/>}/></Form.Item><Form.Item label="密码" name="password" rules={[{required:true}]}><Input.Password size="large"/></Form.Item><Button type="primary" htmlType="submit" size="large" block loading={loading}>登录管理后台</Button></Form></Card></div>}

function Dashboard(){const [data,setData]=useState({listingCount:0,publishedCount:0,appointmentCount:0,pendingCount:0,recentAppointments:[]});useEffect(()=>{api('/admin/dashboard').then(r=>setData(r.data))},[]);return <><PageTitle title="数据概览" desc="实时掌握暖居平台运营情况"/><Row gutter={[16,16]}>{[["房源总数",data.listingCount,<ApartmentOutlined/>],["在租房源",data.publishedCount,<HomeOutlined/>],["累计预约",data.appointmentCount,<CalendarOutlined/>],["待处理预约",data.pendingCount,<TeamOutlined/>]].map(([title,value,icon])=><Col xs={24} sm={12} xl={6} key={title}><Card className="stat-card"><Statistic title={title} value={value} prefix={icon}/></Card></Col>)}</Row><Card title="近期预约" className="section-card"><Table size="middle" rowKey="id" pagination={false} dataSource={data.recentAppointments} columns={appointmentColumns(false)}/></Card></>}

function Listings(){const {message}=AntApp.useApp();const [data,setData]=useState([]);const [loading,setLoading]=useState(false);const [open,setOpen]=useState(false);const [editing,setEditing]=useState(null);const [form]=Form.useForm();const load=()=>{setLoading(true);api('/admin/listings').then(r=>setData(r.data)).catch(e=>message.error(e.message)).finally(()=>setLoading(false))};useEffect(load,[]);const edit=record=>{setEditing(record);form.setFieldsValue({...record,rentType:record.rent_type,imageUrl:record.image_url,reviewCount:record.review_count,landlordName:record.landlord_name,landlordPhone:record.landlord_phone});setOpen(true)};const create=()=>{setEditing(null);form.setFieldsValue(emptyListing);setOpen(true)};const save=async()=>{try{const values=await form.validateFields();await api(editing?`/admin/listings/${editing.id}`:'/admin/listings',{method:editing?'PUT':'POST',body:JSON.stringify(values)});message.success(editing?'房源已更新':'房源已创建');setOpen(false);load()}catch(e){if(!e.errorFields)message.error(e.message)}};const remove=async id=>{try{await api(`/admin/listings/${id}`,{method:'DELETE'});message.success('房源已删除');load()}catch(e){message.error(e.message)}};const columns=[{title:'房源',key:'listing',width:330,render:(_,r)=><Space><Image width={76} height={56} style={{objectFit:'cover',borderRadius:8}} src={r.image_url}/><div><b>{r.title}</b><div className="muted">{r.district} · {r.subway}</div></div></Space>},{title:'租赁',dataIndex:'rent_type',render:v=><Tag color={v==='整租'?'volcano':'blue'}>{v}</Tag>},{title:'户型/面积',render:(_,r)=>`${r.layout} / ${r.area}㎡`},{title:'月租',dataIndex:'price',render:v=><b className="price-text">¥{Number(v).toLocaleString()}</b>},{title:'状态',dataIndex:'status',render:v=><Tag color={v==='published'?'green':'default'}>{v==='published'?'在租':'已下架'}</Tag>},{title:'操作',fixed:'right',render:(_,r)=><Space><Button icon={<EditOutlined/>} onClick={()=>edit(r)}>编辑</Button><Popconfirm title="确定删除该房源？" onConfirm={()=>remove(r.id)}><Button danger icon={<DeleteOutlined/>}/></Popconfirm></Space>}];return <><PageTitle title="房源管理" desc={`共 ${data.length} 套房源`} extra={<Space><Button icon={<ReloadOutlined/>} onClick={load}>刷新</Button><Button type="primary" icon={<PlusOutlined/>} onClick={create}>新增房源</Button></Space>}/><Card><Table rowKey="id" loading={loading} dataSource={data} columns={columns} scroll={{x:1050}}/></Card><Drawer title={editing?'编辑房源':'新增房源'} width={620} open={open} onClose={()=>setOpen(false)} extra={<Button type="primary" onClick={save}>保存</Button>}><ListingForm form={form}/></Drawer></>}

function ListingForm({form}){return <Form form={form} layout="vertical"><Row gutter={14}><Col span={16}><Form.Item label="房源标题" name="title" rules={[{required:true}]}><Input/></Form.Item></Col><Col span={8}><Form.Item label="租赁类型" name="rentType"><Select options={['整租','合租'].map(value=>({value,label:value}))}/></Form.Item></Col><Col span={8}><Form.Item label="区域" name="district"><Input/></Form.Item></Col><Col span={16}><Form.Item label="地铁信息" name="subway"><Input/></Form.Item></Col><Col span={8}><Form.Item label="月租（元）" name="price"><InputNumber min={0} style={{width:'100%'}}/></Form.Item></Col><Col span={8}><Form.Item label="户型" name="layout"><Input/></Form.Item></Col><Col span={8}><Form.Item label="居室数" name="rooms"><InputNumber min={0} style={{width:'100%'}}/></Form.Item></Col><Col span={8}><Form.Item label="面积（㎡）" name="area"><InputNumber min={0} style={{width:'100%'}}/></Form.Item></Col><Col span={8}><Form.Item label="楼层" name="floor"><Input/></Form.Item></Col><Col span={16}><Form.Item label="标签" name="tags"><Select mode="tags" tokenSeparators={[',']} /></Form.Item></Col><Col span={24}><Form.Item label="图片地址" name="imageUrl" rules={[{required:true,type:'url'}]}><Input/></Form.Item></Col><Col span={24}><Form.Item label="房源描述" name="description"><Input.TextArea rows={4}/></Form.Item></Col><Col span={8}><Form.Item label="评分" name="rating"><InputNumber min={0} max={5} step={0.1} style={{width:'100%'}}/></Form.Item></Col><Col span={8}><Form.Item label="评价数" name="reviewCount"><InputNumber min={0} style={{width:'100%'}}/></Form.Item></Col><Col span={8}><Form.Item label="状态" name="status"><Select options={[{value:'published',label:'在租'},{value:'offline',label:'下架'}]}/></Form.Item></Col><Col span={12}><Form.Item label="房东姓名" name="landlordName"><Input/></Form.Item></Col><Col span={12}><Form.Item label="房东电话" name="landlordPhone"><Input/></Form.Item></Col><Col span={12}><Form.Item label="纬度" name="latitude"><InputNumber style={{width:'100%'}}/></Form.Item></Col><Col span={12}><Form.Item label="经度" name="longitude"><InputNumber style={{width:'100%'}}/></Form.Item></Col></Row></Form>}

function Appointments(){const {message}=AntApp.useApp();const [data,setData]=useState([]);const [detail,setDetail]=useState(null);const load=()=>api('/admin/appointments').then(r=>setData(r.data)).catch(e=>message.error(e.message));useEffect(load,[]);const update=async(id,status)=>{await api(`/admin/appointments/${id}`,{method:'PUT',body:JSON.stringify({status})});message.success('预约状态已更新');load()};return <><PageTitle title="预约管理" desc={`共 ${data.length} 条预约`} extra={<Button icon={<ReloadOutlined/>} onClick={load}>刷新</Button>}/><Card><Table rowKey="id" dataSource={data} columns={[...appointmentColumns(true),{title:'操作',render:(_,r)=><Space><Button onClick={()=>setDetail(r)}>详情</Button><Dropdown menu={{items:[{key:'pending',label:'待处理'},{key:'confirmed',label:'已确认'},{key:'completed',label:'已完成'},{key:'cancelled',label:'已取消'}],onClick:({key})=>update(r.id,key)}}><Button type="primary">更新状态</Button></Dropdown></Space>}]} scroll={{x:1000}}/></Card><Modal title="预约详情" open={!!detail} onCancel={()=>setDetail(null)} footer={null}>{detail&&<Descriptions column={1} bordered items={[{key:'1',label:'房源',children:detail.listing_title},{key:'2',label:'预约人',children:detail.name},{key:'3',label:'手机号',children:detail.phone},{key:'4',label:'看房时间',children:dayjs(detail.visit_time).format('YYYY-MM-DD HH:mm')},{key:'5',label:'状态',children:statusTag(detail.status)},{key:'6',label:'提交时间',children:dayjs(detail.created_at).format('YYYY-MM-DD HH:mm')}]}/>}</Modal></>}

const statusTag=status=><Tag color={{pending:'orange',confirmed:'blue',completed:'green',cancelled:'default'}[status]}>{ {pending:'待处理',confirmed:'已确认',completed:'已完成',cancelled:'已取消'}[status]||status}</Tag>;
const appointmentColumns=compact=>[{title:'房源',dataIndex:'listing_title',ellipsis:true},{title:'预约人',dataIndex:'name'},{title:'手机号',dataIndex:'phone'},{title:'看房时间',dataIndex:'visit_time',render:v=>dayjs(v).format('MM-DD HH:mm')},{title:'状态',dataIndex:'status',render:statusTag},...(compact?[]:[{title:'提交时间',dataIndex:'created_at',render:v=>dayjs(v).format('MM-DD HH:mm')}])];
function PageTitle({title,desc,extra}){return <div className="page-title"><div><Typography.Title level={2}>{title}</Typography.Title><Typography.Text type="secondary">{desc}</Typography.Text></div>{extra}</div>}
