// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface WalletStatus$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "WalletStatus";
  readonly sourceName: "contracts/WalletStatus.sol";
  readonly abi: [{"anonymous":false,"inputs":[{"indexed":true,"internalType":"address","name":"account","type":"address"}],"name":"CheckedIn","type":"event"},{"inputs":[],"name":"checkIn","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"address","name":"","type":"address"}],"name":"hasCheckedIn","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"view","type":"function"}];
  readonly bytecode: "0x608060405234801561001057600080fd5b50610119806100206000396000f3fe6080604052348015600f57600080fd5b506004361060325760003560e01c8063183ff0851460375780637f87d6ec14603f575b600080fd5b603d6073565b005b605f604a36600460b5565b60006020819052908152604090205460ff1681565b604051901515815260200160405180910390f35b33600081815260208190526040808220805460ff19166001179055517f591c0e1d11c1207ddcaf435e99150cb7d9c849a2c6d5eae9547cd518cef6a8cd9190a2565b60006020828403121560c657600080fd5b81356001600160a01b038116811460dc57600080fd5b939250505056fea2646970667358221220d71880a1ff5bf3ec34c2145a6f934611e34c438e7cc18622ba9aa3211dc6f25064736f6c63430008180033";
  readonly deployedBytecode: "0x6080604052348015600f57600080fd5b506004361060325760003560e01c8063183ff0851460375780637f87d6ec14603f575b600080fd5b603d6073565b005b605f604a36600460b5565b60006020819052908152604090205460ff1681565b604051901515815260200160405180910390f35b33600081815260208190526040808220805460ff19166001179055517f591c0e1d11c1207ddcaf435e99150cb7d9c849a2c6d5eae9547cd518cef6a8cd9190a2565b60006020828403121560c657600080fd5b81356001600160a01b038116811460dc57600080fd5b939250505056fea2646970667358221220d71880a1ff5bf3ec34c2145a6f934611e34c438e7cc18622ba9aa3211dc6f25064736f6c63430008180033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/WalletStatus.sol";
  readonly buildInfoId: "solc-0_8_24-69804e55ecf6e131a715cb1ef162eecc890f1b2b";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["WalletStatus"]: WalletStatus$Type;
    ["contracts/WalletStatus.sol:WalletStatus"]: WalletStatus$Type;
  }
}